### ISSUE TITLE
support ng-model

### ISSUE THREAD

**Issue by jgallen23** [firstandthird/angular-tokens#1]
`<div tokens ng-model="emails"></div>`

emails should always be in sync with the current values in the tokens input.

**Comment by Antonio-Laguna** [comment]
You already had that with `tokensSuggestions`, changed to use `ng-model`

**Comment by jgallen23** [comment]
No. Token suggestions are for the auto complete. Ng model is for the actual selected values in the token input

**Comment by Antonio-Laguna** [comment]
ohhh ok my bad
